//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karaboss.Resources {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ABCResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ABCResource() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karaboss.Resources.ABCResource", typeof(ABCResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à A:.
        /// </summary>
        internal static string ABCTagAuthor {
            get {
                return ResourceManager.GetString("ABCTagAuthor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à H:.
        /// </summary>
        internal static string ABCTagHistory {
            get {
                return ResourceManager.GetString("ABCTagHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à X:.
        /// </summary>
        internal static string ABCTagIndex {
            get {
                return ResourceManager.GetString("ABCTagIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à K:.
        /// </summary>
        internal static string ABCTagKey {
            get {
                return ResourceManager.GetString("ABCTagKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à W:.
        /// </summary>
        internal static string ABCTagLyrics {
            get {
                return ResourceManager.GetString("ABCTagLyrics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à M:.
        /// </summary>
        internal static string ABCTagMeter {
            get {
                return ResourceManager.GetString("ABCTagMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à N:.
        /// </summary>
        internal static string ABCTagNote {
            get {
                return ResourceManager.GetString("ABCTagNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à O:.
        /// </summary>
        internal static string ABCTagOrigin {
            get {
                return ResourceManager.GetString("ABCTagOrigin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Q:.
        /// </summary>
        internal static string ABCTagTempo {
            get {
                return ResourceManager.GetString("ABCTagTempo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à T:.
        /// </summary>
        internal static string ABCTagTitle {
            get {
                return ResourceManager.GetString("ABCTagTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Z:.
        /// </summary>
        internal static string ABCTagTranscriber {
            get {
                return ResourceManager.GetString("ABCTagTranscriber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à L:.
        /// </summary>
        internal static string ABCTagUnit {
            get {
                return ResourceManager.GetString("ABCTagUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à ABC.
        /// </summary>
        internal static string MusicSubfolder {
            get {
                return ResourceManager.GetString("MusicSubfolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à .
        /// </summary>
        internal static string NewABC {
            get {
                return ResourceManager.GetString("NewABC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à The text in the ABC file has changed. Do you want to save the changes?.
        /// </summary>
        internal static string SavePrompt {
            get {
                return ResourceManager.GetString("SavePrompt", resourceCulture);
            }
        }
    }
}
