//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.18052
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karaboss.Resources.Localization {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Karaboss.Resources.Localization.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à About....
        /// </summary>
        internal static string aboutMenu {
            get {
                return ResourceManager.GetString("aboutMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Cancel.
        /// </summary>
        internal static string cancelButton {
            get {
                return ResourceManager.GetString("cancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Key Signature.
        /// </summary>
        internal static string changeKeyMenu {
            get {
                return ResourceManager.GetString("changeKeyMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Colors....
        /// </summary>
        internal static string chooseColorMenu {
            get {
                return ResourceManager.GetString("chooseColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Note Colors.
        /// </summary>
        internal static string chooseColorsTitle {
            get {
                return ResourceManager.GetString("chooseColorsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Instruments....
        /// </summary>
        internal static string chooseInstrumentsMenu {
            get {
                return ResourceManager.GetString("chooseInstrumentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose Instruments For Each Track.
        /// </summary>
        internal static string chooseInstrumentsTitle {
            get {
                return ResourceManager.GetString("chooseInstrumentsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Close.
        /// </summary>
        internal static string closeMenu {
            get {
                return ResourceManager.GetString("closeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Color.
        /// </summary>
        internal static string colorMenu {
            get {
                return ResourceManager.GetString("colorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combine Notes Within Interval.
        /// </summary>
        internal static string combineNotesMenu {
            get {
                return ResourceManager.GetString("combineNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Combine All Tracks Into Two Staffs.
        /// </summary>
        internal static string combineStaffMenu {
            get {
                return ResourceManager.GetString("combineStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Deselect All Tracks.
        /// </summary>
        internal static string deselectAllTracksMenu {
            get {
                return ResourceManager.GetString("deselectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Down.
        /// </summary>
        internal static string down {
            get {
                return ResourceManager.GetString("down", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à End Measure.
        /// </summary>
        internal static string endMeasure {
            get {
                return ResourceManager.GetString("endMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Exit.
        /// </summary>
        internal static string exitMenu {
            get {
                return ResourceManager.GetString("exitMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fast Forward.
        /// </summary>
        internal static string fastForward {
            get {
                return ResourceManager.GetString("fastForward", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à File.
        /// </summary>
        internal static string fileMenu {
            get {
                return ResourceManager.GetString("fileMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help Contents....
        /// </summary>
        internal static string helpContentsMenu {
            get {
                return ResourceManager.GetString("helpContentsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Help.
        /// </summary>
        internal static string helpMenu {
            get {
                return ResourceManager.GetString("helpMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Large Notes.
        /// </summary>
        internal static string largeNotesMenu {
            get {
                return ResourceManager.GetString("largeNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Measure Length.
        /// </summary>
        internal static string measureMenu {
            get {
                return ResourceManager.GetString("measureMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à milliseconds.
        /// </summary>
        internal static string milliseconds {
            get {
                return ResourceManager.GetString("milliseconds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Mute All Tracks.
        /// </summary>
        internal static string muteAllTracksMenu {
            get {
                return ResourceManager.GetString("muteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à None.
        /// </summary>
        internal static string none {
            get {
                return ResourceManager.GetString("none", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Notes.
        /// </summary>
        internal static string notesMenu {
            get {
                return ResourceManager.GetString("notesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à OK.
        /// </summary>
        internal static string okButton {
            get {
                return ResourceManager.GetString("okButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show One Staff Per Track.
        /// </summary>
        internal static string oneStaffMenu {
            get {
                return ResourceManager.GetString("oneStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open....
        /// </summary>
        internal static string openMenu {
            get {
                return ResourceManager.GetString("openMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Open Sample Song....
        /// </summary>
        internal static string openSampleSongMenu {
            get {
                return ResourceManager.GetString("openSampleSongMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play.
        /// </summary>
        internal static string play {
            get {
                return ResourceManager.GetString("play", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play Measures in a Loop....
        /// </summary>
        internal static string playMeasuresMenu {
            get {
                return ResourceManager.GetString("playMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Play Selected Measures in a Loop.
        /// </summary>
        internal static string playMeasuresTitle {
            get {
                return ResourceManager.GetString("playMeasuresTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print Preview....
        /// </summary>
        internal static string previewMenu {
            get {
                return ResourceManager.GetString("previewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Print....
        /// </summary>
        internal static string printMenu {
            get {
                return ResourceManager.GetString("printMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à pulses.
        /// </summary>
        internal static string pulses {
            get {
                return ResourceManager.GetString("pulses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Rewind.
        /// </summary>
        internal static string rewind {
            get {
                return ResourceManager.GetString("rewind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Choose a Sample MIDI Song.
        /// </summary>
        internal static string sampleSongTitle {
            get {
                return ResourceManager.GetString("sampleSongTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As Images....
        /// </summary>
        internal static string saveImagesMenu {
            get {
                return ResourceManager.GetString("saveImagesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Save As PDF....
        /// </summary>
        internal static string savePDFMenu {
            get {
                return ResourceManager.GetString("savePDFMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll Horizontally.
        /// </summary>
        internal static string scrollHorizMenu {
            get {
                return ResourceManager.GetString("scrollHorizMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Scroll Vertically.
        /// </summary>
        internal static string scrollVertMenu {
            get {
                return ResourceManager.GetString("scrollVertMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select All Tracks.
        /// </summary>
        internal static string selectAllTracksMenu {
            get {
                return ResourceManager.GetString("selectAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Set All To Piano.
        /// </summary>
        internal static string setAllPiano {
            get {
                return ResourceManager.GetString("setAllPiano", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Shift Notes.
        /// </summary>
        internal static string shiftNotesMenu {
            get {
                return ResourceManager.GetString("shiftNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 1/2 note.
        /// </summary>
        internal static string shiftRight12 {
            get {
                return ResourceManager.GetString("shiftRight12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 1/4 note.
        /// </summary>
        internal static string shiftRight14 {
            get {
                return ResourceManager.GetString("shiftRight14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 1/8 note.
        /// </summary>
        internal static string shiftRight18 {
            get {
                return ResourceManager.GetString("shiftRight18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 3/4 note.
        /// </summary>
        internal static string shiftRight34 {
            get {
                return ResourceManager.GetString("shiftRight34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 3/8 note.
        /// </summary>
        internal static string shiftRight38 {
            get {
                return ResourceManager.GetString("shiftRight38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 5/8 note.
        /// </summary>
        internal static string shiftRight58 {
            get {
                return ResourceManager.GetString("shiftRight58", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Right 7/8 note.
        /// </summary>
        internal static string shiftRight78 {
            get {
                return ResourceManager.GetString("shiftRight78", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Default.
        /// </summary>
        internal static string showDefault {
            get {
                return ResourceManager.GetString("showDefault", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed Do-Re-Mi.
        /// </summary>
        internal static string showFixedDoReMi {
            get {
                return ResourceManager.GetString("showFixedDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Fixed Numbers.
        /// </summary>
        internal static string showFixedNumbers {
            get {
                return ResourceManager.GetString("showFixedNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Letters.
        /// </summary>
        internal static string showLetters {
            get {
                return ResourceManager.GetString("showLetters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Note Letters.
        /// </summary>
        internal static string showLettersMenu {
            get {
                return ResourceManager.GetString("showLettersMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Lyrics.
        /// </summary>
        internal static string showLyricsMenu {
            get {
                return ResourceManager.GetString("showLyricsMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Show Measure Numbers.
        /// </summary>
        internal static string showMeasuresMenu {
            get {
                return ResourceManager.GetString("showMeasuresMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Movable Do-Re-Mi.
        /// </summary>
        internal static string showMovableDoReMi {
            get {
                return ResourceManager.GetString("showMovableDoReMi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Movable Numbers.
        /// </summary>
        internal static string showMovableNumbers {
            get {
                return ResourceManager.GetString("showMovableNumbers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Small Notes.
        /// </summary>
        internal static string smallNotesMenu {
            get {
                return ResourceManager.GetString("smallNotesMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Speed.
        /// </summary>
        internal static string speed {
            get {
                return ResourceManager.GetString("speed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Split Track Into Two Staffs.
        /// </summary>
        internal static string splitStaffMenu {
            get {
                return ResourceManager.GetString("splitStaffMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Start Measure.
        /// </summary>
        internal static string startMeasure {
            get {
                return ResourceManager.GetString("startMeasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Stop.
        /// </summary>
        internal static string stop {
            get {
                return ResourceManager.GetString("stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Time Signature.
        /// </summary>
        internal static string timeSigMenu {
            get {
                return ResourceManager.GetString("timeSigMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Tracks to Display.
        /// </summary>
        internal static string trackDisplayMenu {
            get {
                return ResourceManager.GetString("trackDisplayMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Track.
        /// </summary>
        internal static string trackMenu {
            get {
                return ResourceManager.GetString("trackMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Select Tracks to Mute.
        /// </summary>
        internal static string trackMuteMenu {
            get {
                return ResourceManager.GetString("trackMuteMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Transpose.
        /// </summary>
        internal static string transposeMenu {
            get {
                return ResourceManager.GetString("transposeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Unmute All Tracks.
        /// </summary>
        internal static string unmuteAllTracksMenu {
            get {
                return ResourceManager.GetString("unmuteAllTracksMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Up.
        /// </summary>
        internal static string up {
            get {
                return ResourceManager.GetString("up", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Use Color.
        /// </summary>
        internal static string useColorMenu {
            get {
                return ResourceManager.GetString("useColorMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à View.
        /// </summary>
        internal static string viewMenu {
            get {
                return ResourceManager.GetString("viewMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Volume.
        /// </summary>
        internal static string volume {
            get {
                return ResourceManager.GetString("volume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to 100%.
        /// </summary>
        internal static string zoom100Menu {
            get {
                return ResourceManager.GetString("zoom100Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom to 150%.
        /// </summary>
        internal static string zoom150Menu {
            get {
                return ResourceManager.GetString("zoom150Menu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom In.
        /// </summary>
        internal static string zoomInMenu {
            get {
                return ResourceManager.GetString("zoomInMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à Zoom Out.
        /// </summary>
        internal static string zoomOutMenu {
            get {
                return ResourceManager.GetString("zoomOutMenu", resourceCulture);
            }
        }

		internal static string addToPlaylist
        {
            get
            {
                return ResourceManager.GetString("addToPlaylist", resourceCulture);
            }
        }

        internal static string deleteMenu
        {
            get
            {
                return ResourceManager.GetString("deleteMenu", resourceCulture);
            }
        }

        internal static string newFolderMenu
        {
            get
            {
                return ResourceManager.GetString("newFolderMenu", resourceCulture);
            }
        }
        
        
        internal static string QuitApplication
        {
            get
            {
                return ResourceManager.GetString("QuitApplication", resourceCulture);
            }
        }

        internal static string renameAllMenu
        {
            get
            {
                return ResourceManager.GetString("renameAllMenu", resourceCulture);
            }
        }

        internal static string renameMenu
        {
            get
            {
                return ResourceManager.GetString("renameMenu", resourceCulture);
            }
        }

        internal static string replaceAllMenu
        {
            get
            {
                return ResourceManager.GetString("replaceAllMenu", resourceCulture);
            }
        }

        internal static string refreshDisplayMenu
        {
            get
            {
                return ResourceManager.GetString("refreshDisplayMenu", resourceCulture);
            }
        }


        internal static string edit
        {
            get
            {
                return ResourceManager.GetString("edit", resourceCulture);
            }
        }

        internal static string fileName
        {
            get
            {
                return ResourceManager.GetString("fileName", resourceCulture);
            }
        }
        internal static string Modified
        {
            get
            {
                return ResourceManager.GetString("Modified", resourceCulture);
            }
        }
        internal static string Size
        {
            get
            {
                return ResourceManager.GetString("Size", resourceCulture);
            }
        }
        internal static string Type
        {
            get
            {
                return ResourceManager.GetString("Type", resourceCulture);
            }
        }
        internal static string Singer
        {
            get
            {
                return ResourceManager.GetString("Singer", resourceCulture);
            }
        }

        internal static string Language
        {
            get
            {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        internal static string SongTextEncoding
        {
            get
            {
                return ResourceManager.GetString("SongTextEncoding", resourceCulture);
            }
        }
        
        internal static string KaraokeOptions
        {
            get
            {
                return ResourceManager.GetString("KaraokeOptions", resourceCulture);
            }
        }
        internal static string UpdateKaraboss
        {
            get
            {
                return ResourceManager.GetString("UpdateKaraboss", resourceCulture);
            }
        }
        internal static string MidiEditor
        {
            get
            {
                return ResourceManager.GetString("MidiEditor", resourceCulture);
            }
        }
        internal static string NewPlaylist
        {
            get
            {
                return ResourceManager.GetString("NewPlaylist", resourceCulture);
            }
        }
        internal static string CreateNewPlaylist
        {
            get
            {
                return ResourceManager.GetString("CreateNewPlaylist", resourceCulture);
            }
        }
        internal static string AddSongToNewPlaylist
        {
            get
            {
                return ResourceManager.GetString("AddSongToNewPlaylist", resourceCulture);
            }
        }
        internal static string OpenFolder
        {
            get
            {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        internal static string Duration
        {
            get
            {
                return ResourceManager.GetString("Duration", resourceCulture);
            }
        }
        internal static string Copy
        {
            get
            {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        internal static string Paste
        {
            get
            {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        internal static string InsertNewLine
        {
            get
            {
                return ResourceManager.GetString("InsertNewLine", resourceCulture);
            }
        }
        internal static string InsertLineBreak
        {
            get
            {
                return ResourceManager.GetString("InsertLineBreak", resourceCulture);
            }
        }
        internal static string InsertNewParagraph
        {
            get
            {
                return ResourceManager.GetString("InsertNewParagraph", resourceCulture);
            }
        }
        internal static string OffsetUp
        {
            get
            {
                return ResourceManager.GetString("OffsetUp", resourceCulture);
            }
        }
        internal static string OffsetDown
        {
            get
            {
                return ResourceManager.GetString("OffsetDown", resourceCulture);
            }
        }
        internal static string DeleteLine
        {
            get
            {
                return ResourceManager.GetString("DeleteLine", resourceCulture);
            }
        }
        internal static string SungBy
        {
            get
            {
                return ResourceManager.GetString("SungBy", resourceCulture);
            }
        }
        internal static string InsertMeasures
        {
            get
            {
                return ResourceManager.GetString("InsertMeasures", resourceCulture);
            }
        }
        internal static string ThisTrack
        {
            get
            {
                return ResourceManager.GetString("ThisTrack", resourceCulture);
            }
        }
        internal static string AllTrack
        {
            get
            {
                return ResourceManager.GetString("AllTracks", resourceCulture);
            }
        }
        internal static string DeleteMeasures
        {
            get
            {
                return ResourceManager.GetString("DeleteMeasures", resourceCulture);
            }
        }
        internal static string InsertOneTime
        {
            get
            {
                return ResourceManager.GetString("InsertOneTime", resourceCulture);
            }
        }
        internal static string InsertHalfTime
        {
            get
            {
                return ResourceManager.GetString("InsertHalfTime", resourceCulture);
            }
        }
        internal static string DeleteOneTime
        {
            get
            {
                return ResourceManager.GetString("DeleteOneTime", resourceCulture);
            }
        }
        internal static string DeleteHalfTime
        {
            get
            {
                return ResourceManager.GetString("DeleteHalfTime", resourceCulture);
            }
        }
        internal static string SelectMeasures
        {
            get
            {
                return ResourceManager.GetString("SelectMeasures", resourceCulture);
            }
        }
        internal static string NoMelodyTrack
        {
            get
            {
                return ResourceManager.GetString("NoMelodyTrack", resourceCulture);
            }
        }        
        internal static string MusicSubfolder
        {
            get
            {
                return ResourceManager.GetString("MusicSubfolder", resourceCulture);
            }
        }
        internal static string DeleteAllLyrics
        {
            get
            {
                return ResourceManager.GetString("DeleteAllLyrics", resourceCulture);
            }
        }
        internal static string OffsetStartTimesOfNotes
        {
            get
            {
                return ResourceManager.GetString("OffsetStartTimesOfNotes", resourceCulture);                
            }
        }
        internal static string SubDirectoryForbiden
        {
            get
            {
                return ResourceManager.GetString("SubDirectoryForbiden", resourceCulture);
            }
        }
        internal static string SearchRecursively
        {
            get
            {
                return ResourceManager.GetString("SearchRecursively", resourceCulture);
            }
        }
        internal static string SearchMD5Doubles
        {
            get
            {
                return ResourceManager.GetString("SearchMD5Doubles", resourceCulture);
            }
        }
        internal static string SearchMD5DoublesL1
        {
            get
            {
                return ResourceManager.GetString("SearchMD5DoublesL1", resourceCulture);
            }
        }
        internal static string SearchMD5DoublesL2
        {
            get
            {
                return ResourceManager.GetString("SearchMD5DoublesL2", resourceCulture);
            }
        }
        internal static string SearchMD5DoublesL3
        {
            get
            {
                return ResourceManager.GetString("SearchMD5DoublesL3", resourceCulture);
            }
        }
        internal static string SearchMD5DoublesSel
        {
            get
            {
                return ResourceManager.GetString("SearchMD5DoublesSel", resourceCulture);
            }
        }
    }
}
