//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Karaboss.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.14.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        /// <summary>
        /// Default directory
        /// </summary>
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Configuration.SettingsDescriptionAttribute("Default directory")]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string StartDirectory {
            get {
                return ((string)(this["StartDirectory"]));
            }
            set {
                this["StartDirectory"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMainMaximized {
            get {
                return ((bool)(this["frmMainMaximized"]));
            }
            set {
                this["frmMainMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMainLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMainLocation"]));
            }
            set {
                this["frmMainLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmMainSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMainSize"]));
            }
            set {
                this["frmMainSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmPlayerMaximized {
            get {
                return ((bool)(this["frmPlayerMaximized"]));
            }
            set {
                this["frmPlayerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmPlayerLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmPlayerLocation"]));
            }
            set {
                this["frmPlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size frmPlayerSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPlayerSize"]));
            }
            set {
                this["frmPlayerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int frmMainSplitterDistance {
            get {
                return ((int)(this["frmMainSplitterDistance"]));
            }
            set {
                this["frmMainSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmScoreMaximized {
            get {
                return ((bool)(this["frmScoreMaximized"]));
            }
            set {
                this["frmScoreMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmScoreLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmScoreLocation"]));
            }
            set {
                this["frmScoreLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 800")]
        public global::System.Drawing.Size frmScoreSize {
            get {
                return ((global::System.Drawing.Size)(this["frmScoreSize"]));
            }
            set {
                this["frmScoreSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLyricMaximized {
            get {
                return ((bool)(this["frmLyricMaximized"]));
            }
            set {
                this["frmLyricMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 200")]
        public global::System.Drawing.Point frmLyricLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmLyricLocation"]));
            }
            set {
                this["frmLyricLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size frmLyricSize {
            get {
                return ((global::System.Drawing.Size)(this["frmLyricSize"]));
            }
            set {
                this["frmLyricSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLyricsMaximized {
            get {
                return ((bool)(this["frmLyricsMaximized"]));
            }
            set {
                this["frmLyricsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmLyricsLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmLyricsLocation"]));
            }
            set {
                this["frmLyricsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("400, 600")]
        public global::System.Drawing.Size frmLyricsSize {
            get {
                return ((global::System.Drawing.Size)(this["frmLyricsSize"]));
            }
            set {
                this["frmLyricsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TxtBackColor {
            get {
                return ((global::System.Drawing.Color)(this["TxtBackColor"]));
            }
            set {
                this["TxtBackColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("White")]
        public global::System.Drawing.Color TxtNextColor {
            get {
                return ((global::System.Drawing.Color)(this["TxtNextColor"]));
            }
            set {
                this["TxtNextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color TxtHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["TxtHighlightColor"]));
            }
            set {
                this["TxtHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("YellowGreen")]
        public global::System.Drawing.Color TxtBeforeColor {
            get {
                return ((global::System.Drawing.Color)(this["TxtBeforeColor"]));
            }
            set {
                this["TxtBeforeColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLyricsEditMaximized {
            get {
                return ((bool)(this["frmLyricsEditMaximized"]));
            }
            set {
                this["frmLyricsEditMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmLyricsEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmLyricsEditLocation"]));
            }
            set {
                this["frmLyricsEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("760, 500")]
        public global::System.Drawing.Size frmLyricsEditSize {
            get {
                return ((global::System.Drawing.Size)(this["frmLyricsEditSize"]));
            }
            set {
                this["frmLyricsEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public int TxtNbLines {
            get {
                return ((int)(this["TxtNbLines"]));
            }
            set {
                this["TxtNbLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string dirSlideShow {
            get {
                return ((string)(this["dirSlideShow"]));
            }
            set {
                this["dirSlideShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TxtContourColor {
            get {
                return ((global::System.Drawing.Color)(this["TxtContourColor"]));
            }
            set {
                this["TxtContourColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10")]
        public int freqSlideShow {
            get {
                return ((int)(this["freqSlideShow"]));
            }
            set {
                this["freqSlideShow"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("StretchImage")]
        public global::System.Windows.Forms.PictureBoxSizeMode SizeMode {
            get {
                return ((global::System.Windows.Forms.PictureBoxSizeMode)(this["SizeMode"]));
            }
            set {
                this["SizeMode"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Ascii")]
        public string textEncoding {
            get {
                return ((string)(this["textEncoding"]));
            }
            set {
                this["textEncoding"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Undefined")]
        public string lang {
            get {
                return ((string)(this["lang"]));
            }
            set {
                this["lang"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool MuteMelody {
            get {
                return ((bool)(this["MuteMelody"]));
            }
            set {
                this["MuteMelody"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string filePlaylists {
            get {
                return ((string)(this["filePlaylists"]));
            }
            set {
                this["filePlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"C:\\\\\"")]
        public string drivePlaylists {
            get {
                return ((string)(this["drivePlaylists"]));
            }
            set {
                this["drivePlaylists"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowSequencer {
            get {
                return ((bool)(this["ShowSequencer"]));
            }
            set {
                this["ShowSequencer"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool ShowKaraoke {
            get {
                return ((bool)(this["ShowKaraoke"]));
            }
            set {
                this["ShowKaraoke"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Diaporama\"")]
        public string BackGroundOption {
            get {
                return ((string)(this["BackGroundOption"]));
            }
            set {
                this["BackGroundOption"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmPianoRollMaximized {
            get {
                return ((bool)(this["frmPianoRollMaximized"]));
            }
            set {
                this["frmPianoRollMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmPianoRollLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmPianoRollLocation"]));
            }
            set {
                this["frmPianoRollLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("760, 500")]
        public global::System.Drawing.Size frmPianoRollSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPianoRollSize"]));
            }
            set {
                this["frmPianoRollSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string SongRoot {
            get {
                return ((string)(this["SongRoot"]));
            }
            set {
                this["SongRoot"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int lvFileNameColumn {
            get {
                return ((int)(this["lvFileNameColumn"]));
            }
            set {
                this["lvFileNameColumn"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmSearchMaximized {
            get {
                return ((bool)(this["frmSearchMaximized"]));
            }
            set {
                this["frmSearchMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmSearchLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmSearchLocation"]));
            }
            set {
                this["frmSearchLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("677, 334")]
        public global::System.Drawing.Size frmSearchSize {
            get {
                return ((global::System.Drawing.Size)(this["frmSearchSize"]));
            }
            set {
                this["frmSearchSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool CheckForUpdates {
            get {
                return ((bool)(this["CheckForUpdates"]));
            }
            set {
                this["CheckForUpdates"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("https://karaboss.lacharme.net/AutoupdateService.xml")]
        public string RemoteUrl {
            get {
                return ((string)(this["RemoteUrl"]));
            }
            set {
                this["RemoteUrl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmCDGLyricsMaximized {
            get {
                return ((bool)(this["frmCDGLyricsMaximized"]));
            }
            set {
                this["frmCDGLyricsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmCDGLyricsLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmCDGLyricsLocation"]));
            }
            set {
                this["frmCDGLyricsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 400")]
        public global::System.Drawing.Size frmCDGLyricsSize {
            get {
                return ((global::System.Drawing.Size)(this["frmCDGLyricsSize"]));
            }
            set {
                this["frmCDGLyricsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmCDGPlayerLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmCDGPlayerLocation"]));
            }
            set {
                this["frmCDGPlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Monthly")]
        public string UpdFrequency {
            get {
                return ((string)(this["UpdFrequency"]));
            }
            set {
                this["UpdFrequency"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public global::System.DateTime lastUpdCheck {
            get {
                return ((global::System.DateTime)(this["lastUpdCheck"]));
            }
            set {
                this["lastUpdCheck"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmExplorerMaximized {
            get {
                return ((bool)(this["frmExplorerMaximized"]));
            }
            set {
                this["frmExplorerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmExplorerLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmExplorerLocation"]));
            }
            set {
                this["frmExplorerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1200, 800")]
        public global::System.Drawing.Size frmExplorerSize {
            get {
                return ((global::System.Drawing.Size)(this["frmExplorerSize"]));
            }
            set {
                this["frmExplorerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300")]
        public int frmExplorerSplitterDistance {
            get {
                return ((int)(this["frmExplorerSplitterDistance"]));
            }
            set {
                this["frmExplorerSplitterDistance"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool RetrieveSettings {
            get {
                return ((bool)(this["RetrieveSettings"]));
            }
            set {
                this["RetrieveSettings"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmPrintMaximized {
            get {
                return ((bool)(this["frmPrintMaximized"]));
            }
            set {
                this["frmPrintMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmPrintLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmPrintLocation"]));
            }
            set {
                this["frmPrintLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmPrintSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPrintSize"]));
            }
            set {
                this["frmPrintSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string filePlaylistGroups {
            get {
                return ((string)(this["filePlaylistGroups"]));
            }
            set {
                this["filePlaylistGroups"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://myproxy.fr:8080")]
        public string ProxyAddress {
            get {
                return ((string)(this["ProxyAddress"]));
            }
            set {
                this["ProxyAddress"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UserName")]
        public string ProxyUserName {
            get {
                return ((string)(this["ProxyUserName"]));
            }
            set {
                this["ProxyUserName"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Password")]
        public string ProxyPassword {
            get {
                return ((string)(this["ProxyPassword"]));
            }
            set {
                this["ProxyPassword"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmPianoTrainingMaximized {
            get {
                return ((bool)(this["frmPianoTrainingMaximized"]));
            }
            set {
                this["frmPianoTrainingMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmPianoTrainingLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmPianoTrainingLocation"]));
            }
            set {
                this["frmPianoTrainingLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmPianoTrainingSize {
            get {
                return ((global::System.Drawing.Size)(this["frmPianoTrainingSize"]));
            }
            set {
                this["frmPianoTrainingSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool DisplayBalls {
            get {
                return ((bool)(this["DisplayBalls"]));
            }
            set {
                this["DisplayBalls"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\"Center\"")]
        public string LyricsOptionDisplay {
            get {
                return ((string)(this["LyricsOptionDisplay"]));
            }
            set {
                this["LyricsOptionDisplay"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLyricsBackGround {
            get {
                return ((bool)(this["bLyricsBackGround"]));
            }
            set {
                this["bLyricsBackGround"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bPauseBetweenSongs {
            get {
                return ((bool)(this["bPauseBetweenSongs"]));
            }
            set {
                this["bPauseBetweenSongs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int CountdownSongs {
            get {
                return ((int)(this["CountdownSongs"]));
            }
            set {
                this["CountdownSongs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int TransposeAmount {
            get {
                return ((int)(this["TransposeAmount"]));
            }
            set {
                this["TransposeAmount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public int Velocity {
            get {
                return ((int)(this["Velocity"]));
            }
            set {
                this["Velocity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmGuitarTrainingMaximized {
            get {
                return ((bool)(this["frmGuitarTrainingMaximized"]));
            }
            set {
                this["frmGuitarTrainingMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmGuitarTrainingLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmGuitarTrainingLocation"]));
            }
            set {
                this["frmGuitarTrainingLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmGuitarTrainingSize {
            get {
                return ((global::System.Drawing.Size)(this["frmGuitarTrainingSize"]));
            }
            set {
                this["frmGuitarTrainingSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PianoRollZoomX {
            get {
                return ((float)(this["PianoRollZoomX"]));
            }
            set {
                this["PianoRollZoomX"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float PianoRollZoomY {
            get {
                return ((float)(this["PianoRollZoomY"]));
            }
            set {
                this["PianoRollZoomY"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bColorContour {
            get {
                return ((bool)(this["bColorContour"]));
            }
            set {
                this["bColorContour"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Comic Sans MS, 8.25pt")]
        public global::System.Drawing.Font KaraokeFont {
            get {
                return ((global::System.Drawing.Font)(this["KaraokeFont"]));
            }
            set {
                this["KaraokeFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("*")]
        public string SepSyllabe {
            get {
                return ((string)(this["SepSyllabe"]));
            }
            set {
                this["SepSyllabe"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("/")]
        public string SepLine {
            get {
                return ((string)(this["SepLine"]));
            }
            set {
                this["SepLine"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("\\")]
        public string SepParagraph {
            get {
                return ((string)(this["SepParagraph"]));
            }
            set {
                this["SepParagraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string FavoriteSongs {
            get {
                return ((string)(this["FavoriteSongs"]));
            }
            set {
                this["FavoriteSongs"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("746, 618")]
        public global::System.Drawing.Size FrmABCnotationSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmABCnotationSize"]));
            }
            set {
                this["FrmABCnotationSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100, 100")]
        public global::System.Drawing.Point FrmABCnotationLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmABCnotationLocation"]));
            }
            set {
                this["FrmABCnotationLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmABCnotationAOT {
            get {
                return ((bool)(this["FrmABCnotationAOT"]));
            }
            set {
                this["FrmABCnotationAOT"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool LoadABCAtStartup {
            get {
                return ((bool)(this["LoadABCAtStartup"]));
            }
            set {
                this["LoadABCAtStartup"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TagsEdit {
            get {
                return ((string)(this["TagsEdit"]));
            }
            set {
                this["TagsEdit"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string TagsPerform {
            get {
                return ((string)(this["TagsPerform"]));
            }
            set {
                this["TagsPerform"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool HighlightABC {
            get {
                return ((bool)(this["HighlightABC"]));
            }
            set {
                this["HighlightABC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Toolbars {
            get {
                return ((string)(this["Toolbars"]));
            }
            set {
                this["Toolbars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point FrmTextPlayerLocation {
            get {
                return ((global::System.Drawing.Point)(this["FrmTextPlayerLocation"]));
            }
            set {
                this["FrmTextPlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool FrmTextPlayerMaximized {
            get {
                return ((bool)(this["FrmTextPlayerMaximized"]));
            }
            set {
                this["FrmTextPlayerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size FrmTextPlayerSize {
            get {
                return ((global::System.Drawing.Size)(this["FrmTextPlayerSize"]));
            }
            set {
                this["FrmTextPlayerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool ShowTextEditor {
            get {
                return ((bool)(this["ShowTextEditor"]));
            }
            set {
                this["ShowTextEditor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveDefaultOutputDevice {
            get {
                return ((bool)(this["SaveDefaultOutputDevice"]));
            }
            set {
                this["SaveDefaultOutputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int DefaultOutputDevice {
            get {
                return ((int)(this["DefaultOutputDevice"]));
            }
            set {
                this["DefaultOutputDevice"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowParagraph {
            get {
                return ((bool)(this["bShowParagraph"]));
            }
            set {
                this["bShowParagraph"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bForceUppercase {
            get {
                return ((bool)(this["bForceUppercase"]));
            }
            set {
                this["bForceUppercase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmChordsLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmChordsLocation"]));
            }
            set {
                this["frmChordsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size frmChordsSize {
            get {
                return ((global::System.Drawing.Size)(this["frmChordsSize"]));
            }
            set {
                this["frmChordsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmChordsMaximized {
            get {
                return ((bool)(this["frmChordsMaximized"]));
            }
            set {
                this["frmChordsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Segoe UI, 9pt")]
        public global::System.Drawing.Font LyricsEditFont {
            get {
                return ((global::System.Drawing.Font)(this["LyricsEditFont"]));
            }
            set {
                this["LyricsEditFont"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("255, 196, 13")]
        public global::System.Drawing.Color ChordNextColor {
            get {
                return ((global::System.Drawing.Color)(this["ChordNextColor"]));
            }
            set {
                this["ChordNextColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Red")]
        public global::System.Drawing.Color ChordHighlightColor {
            get {
                return ((global::System.Drawing.Color)(this["ChordHighlightColor"]));
            }
            set {
                this["ChordHighlightColor"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bShowChords {
            get {
                return ((bool)(this["bShowChords"]));
            }
            set {
                this["bShowChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bShowXmlChords {
            get {
                return ((bool)(this["bShowXmlChords"]));
            }
            set {
                this["bShowXmlChords"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("100")]
        public decimal ChordsMapCellSize {
            get {
                return ((decimal)(this["ChordsMapCellSize"]));
            }
            set {
                this["ChordsMapCellSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public decimal ChordsMapColumns {
            get {
                return ((decimal)(this["ChordsMapColumns"]));
            }
            set {
                this["ChordsMapColumns"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ChordsMapZoom {
            get {
                return ((float)(this["ChordsMapZoom"]));
            }
            set {
                this["ChordsMapZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public float ChordsMapModifyZoom {
            get {
                return ((float)(this["ChordsMapModifyZoom"]));
            }
            set {
                this["ChordsMapModifyZoom"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLrcForceUpperCase {
            get {
                return ((bool)(this["bLrcForceUpperCase"]));
            }
            set {
                this["bLrcForceUpperCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLrcRemoveAccents {
            get {
                return ((bool)(this["bLrcRemoveAccents"]));
            }
            set {
                this["bLrcRemoveAccents"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLrcRemoveNonAlphaNumeric {
            get {
                return ((bool)(this["bLrcRemoveNonAlphaNumeric"]));
            }
            set {
                this["bLrcRemoveNonAlphaNumeric"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int lrcFormatLinesSyllabes {
            get {
                return ((int)(this["lrcFormatLinesSyllabes"]));
            }
            set {
                this["lrcFormatLinesSyllabes"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLrcCutLines {
            get {
                return ((bool)(this["bLrcCutLines"]));
            }
            set {
                this["bLrcCutLines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("32")]
        public int LrcCutLinesChars {
            get {
                return ((int)(this["LrcCutLinesChars"]));
            }
            set {
                this["LrcCutLinesChars"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bLrcForceLowerCase {
            get {
                return ((bool)(this["bLrcForceLowerCase"]));
            }
            set {
                this["bLrcForceLowerCase"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMp3PlayerLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMp3PlayerLocation"]));
            }
            set {
                this["frmMp3PlayerLocation"] = value;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("fabrice.lacharme@gmail.com")]
        public string BassRegistrationEmail {
            get {
                return ((string)(this["BassRegistrationEmail"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2X1632326152222")]
        public string BassRegistrationKey {
            get {
                return ((string)(this["BassRegistrationKey"]));
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMp3LyricsLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMp3LyricsLocation"]));
            }
            set {
                this["frmMp3LyricsLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMp3LyricsMaximized {
            get {
                return ((bool)(this["frmMp3LyricsMaximized"]));
            }
            set {
                this["frmMp3LyricsMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmMp3LyricsSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMp3LyricsSize"]));
            }
            set {
                this["frmMp3LyricsSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMp3LyricsEditLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMp3LyricsEditLocation"]));
            }
            set {
                this["frmMp3LyricsEditLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMp3LyricsEditMaximized {
            get {
                return ((bool)(this["frmMp3LyricsEditMaximized"]));
            }
            set {
                this["frmMp3LyricsEditMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800, 600")]
        public global::System.Drawing.Size frmMp3LyricsEditSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMp3LyricsEditSize"]));
            }
            set {
                this["frmMp3LyricsEditSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool bProgressiveHighlight {
            get {
                return ((bool)(this["bProgressiveHighlight"]));
            }
            set {
                this["bProgressiveHighlight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int LrcMillisecondsDigits {
            get {
                return ((int)(this["LrcMillisecondsDigits"]));
            }
            set {
                this["LrcMillisecondsDigits"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmLrcGeneratorLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmLrcGeneratorLocation"]));
            }
            set {
                this["frmLrcGeneratorLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLrcGeneratorMaximized {
            get {
                return ((bool)(this["frmLrcGeneratorMaximized"]));
            }
            set {
                this["frmLrcGeneratorMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("675, 530")]
        public global::System.Drawing.Size frmLrcGeneratorSize {
            get {
                return ((global::System.Drawing.Size)(this["frmLrcGeneratorSize"]));
            }
            set {
                this["frmLrcGeneratorSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMp3PlayerMaximized {
            get {
                return ((bool)(this["frmMp3PlayerMaximized"]));
            }
            set {
                this["frmMp3PlayerMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmMp3PlayerSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMp3PlayerSize"]));
            }
            set {
                this["frmMp3PlayerSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bExportMetadata {
            get {
                return ((bool)(this["bExportMetadata"]));
            }
            set {
                this["bExportMetadata"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0, 0")]
        public global::System.Drawing.Point frmMp3LyricsSimpleLocation {
            get {
                return ((global::System.Drawing.Point)(this["frmMp3LyricsSimpleLocation"]));
            }
            set {
                this["frmMp3LyricsSimpleLocation"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmMp3LyricsSimpleMaximized {
            get {
                return ((bool)(this["frmMp3LyricsSimpleMaximized"]));
            }
            set {
                this["frmMp3LyricsSimpleMaximized"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600, 600")]
        public global::System.Drawing.Size frmMp3LyricsSimpleSize {
            get {
                return ((global::System.Drawing.Size)(this["frmMp3LyricsSimpleSize"]));
            }
            set {
                this["frmMp3LyricsSimpleSize"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool frmLyricsTopMost {
            get {
                return ((bool)(this["frmLyricsTopMost"]));
            }
            set {
                this["frmLyricsTopMost"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("MediumTurquoise")]
        public global::System.Drawing.Color TxtGrad0Color {
            get {
                return ((global::System.Drawing.Color)(this["TxtGrad0Color"]));
            }
            set {
                this["TxtGrad0Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("GreenYellow")]
        public global::System.Drawing.Color TxtGrad1Color {
            get {
                return ((global::System.Drawing.Color)(this["TxtGrad1Color"]));
            }
            set {
                this["TxtGrad1Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Black")]
        public global::System.Drawing.Color TxtRhythm0Color {
            get {
                return ((global::System.Drawing.Color)(this["TxtRhythm0Color"]));
            }
            set {
                this["TxtRhythm0Color"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("DodgerBlue")]
        public global::System.Drawing.Color TxtRhythm1Color {
            get {
                return ((global::System.Drawing.Color)(this["TxtRhythm1Color"]));
            }
            set {
                this["TxtRhythm1Color"] = value;
            }
        }
    }
}
